/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spk.mfep;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class ProsesData extends javax.swing.JFrame {

    /**
     * Creates new form ProsesData
     */
    public ProsesData() {
        initComponents();
        setLocationRelativeTo(this);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        tampil_data();
    }
private DefaultTableModel tabmode;
DefaultTableModel tabelNormalisasi;
DefaultTableModel tabelPeringkat;

 koneksi conn= new koneksi();

public void tampil_data(){
       tabmode = new DefaultTableModel();
       tabmode.addColumn("NIK");
       tabmode.addColumn("Nama");
       tabmode.addColumn("Alamat");
       tabmode.addColumn("Umur");
       tabmode.addColumn("Penghasilan");
       tabmode.addColumn("Pekerjaan");
       tabmode.addColumn("Jenis Rumah");
       tabmode.addColumn("Daya Listrik");
       tbl_datawarga.setModel(tabmode);
        try {
         ResultSet res = conn.ambilData("SELECT * FROM tbl_kriteria ");
        while (res.next()){
                    tabmode.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),
                        res.getString(6),res.getString(7),res.getString(8)});
                }
        tbl_datawarga.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datawarga = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_normalisasi = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_peringkat = new javax.swing.JTable();
        btn_kesimpulan = new javax.swing.JButton();
        btn_normalisasi = new javax.swing.JButton();
        btn_peringkat = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Proses Data");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATA WARGA");

        tbl_datawarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_datawarga);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("NORMALISASI");

        tbl_normalisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_normalisasi);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("PERINGKAT");

        tbl_peringkat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_peringkat);

        btn_kesimpulan.setBackground(new java.awt.Color(51, 204, 255));
        btn_kesimpulan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kesimpulan.setForeground(new java.awt.Color(255, 255, 255));
        btn_kesimpulan.setText("KESIMPULAN");
        btn_kesimpulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kesimpulanActionPerformed(evt);
            }
        });

        btn_normalisasi.setBackground(new java.awt.Color(51, 204, 255));
        btn_normalisasi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_normalisasi.setForeground(new java.awt.Color(255, 255, 255));
        btn_normalisasi.setText("Normalisasikan");
        btn_normalisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalisasiActionPerformed(evt);
            }
        });

        btn_peringkat.setBackground(new java.awt.Color(51, 204, 255));
        btn_peringkat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_peringkat.setForeground(new java.awt.Color(255, 255, 255));
        btn_peringkat.setText("Tentukan Peringkat");
        btn_peringkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_peringkatActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(51, 204, 255));
        btn_print.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_print)
                                .addGap(27, 27, 27)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_normalisasi))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_peringkat)))))
                        .addGap(112, 133, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kesimpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btn_kesimpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_normalisasi)
                        .addComponent(jLabel7)
                        .addComponent(btn_peringkat))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btn_print))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_peringkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_peringkatActionPerformed
        // TODO add your handling code here:
        cariperingkat();
    }//GEN-LAST:event_btn_peringkatActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_normalisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalisasiActionPerformed
        // TODO add your handling code here:
        normalisasi();
    }//GEN-LAST:event_btn_normalisasiActionPerformed

    private void btn_kesimpulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kesimpulanActionPerformed
        // TODO add your handling code here:
        kesimpulan kesimpulan_ = new kesimpulan();
        kesimpulan_.setVisible(true);
    }//GEN-LAST:event_btn_kesimpulanActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        try {
            MessageFormat header = new MessageFormat ("DATA HASIL PERANGKINGAN");
            MessageFormat footer = new MessageFormat (" ");

            tbl_peringkat.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Print GAGAL");
        }
    }//GEN-LAST:event_btn_printActionPerformed

        public void tabelModelNormalisasi(){
       tabelNormalisasi = new DefaultTableModel();
       tabelNormalisasi.addColumn("NIK");
       tabelNormalisasi.addColumn("Nama");
       tabelNormalisasi.addColumn("Umur");
       tabelNormalisasi.addColumn("Penghasilan");
       tabelNormalisasi.addColumn("Pekerjaan");
       tabelNormalisasi.addColumn("Jenis Rumah");
       tabelNormalisasi.addColumn("Daya Listrik");
       tbl_normalisasi.setModel(tabelNormalisasi);
    }
    
     public void tabelmodelPeringkat(){
        try {
            tabelPeringkat = new DefaultTableModel();
            tabelPeringkat.addColumn("NIK");
            tabelPeringkat.addColumn("Nama");
            tabelPeringkat.addColumn("Nilai");
            
            tbl_peringkat.setModel(tabelPeringkat);
            ResultSet res = conn.ambilData("SELECT * FROM tbl_peringkat ORDER BY Nilai desc");
             while (res.next()){
                         tabelPeringkat.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)}); 
                     }
        } catch (SQLException ex) {
            Logger.getLogger(ProsesData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cariperingkat(){
        try{
            LinkedList mm = new LinkedList();
            ResultSet res3 = conn.ambilData("SELECT * FROM tbl_bobot");
            tabelmodelPeringkat();
            while (res3.next()){
                 mm.add(res3.getString(1));
                 mm.add(res3.getString(2));
                 mm.add(res3.getString(3));
                 mm.add(res3.getString(4));
                 mm.add(res3.getString(5));
            }
            for (int t = 0; t < tbl_normalisasi.getRowCount(); t++) {
                String sql = "DELETE FROM tbl_peringkat WHERE NIK= NIK";
                conn.simpanData(sql);
            }
            for (int x = 0; x < tbl_normalisasi.getRowCount(); x++){
                double r1;
                double r2;
                double r3;
                double r4;
                double r5;
                double w;
                
                r1=(Float.valueOf(tbl_normalisasi.getValueAt(x, 2).toString()));
                r2=(Float.valueOf(tbl_normalisasi.getValueAt(x, 3).toString()));
                r3=(Float.valueOf(tbl_normalisasi.getValueAt(x, 4).toString()));
                r4=(Float.valueOf(tbl_normalisasi.getValueAt(x, 5).toString()));
                r5=(Float.valueOf(tbl_normalisasi.getValueAt(x, 6).toString()));
                w=r1+r2+r3+r4+r5;
                
                String sql = "insert into tbl_peringkat  values"+"(  '"+tbl_normalisasi.getValueAt(x, 0).toString()+"', "+" '"+tbl_normalisasi.getValueAt(x, 1).toString()+"', "+" '"+w+"' )";
                conn.simpanData(sql);
            }
            tabelModelNormalisasi();
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public  void normalisasi(){
        LinkedList max = new LinkedList();
        LinkedList mm = new LinkedList();
        
        try{
            ResultSet res = conn.ambilData("select (b1),"+ 
                "(b2), "+
                "(b3), "+
                "(b4),"+
                "(b5)"+
                "from "+
                "tbl_bobot ");
            
            while (res.next()){
                max.add(res.getString(1));
                max.add(res.getString(2));
                max.add(res.getString(3));
                max.add(res.getString(4));
                max.add(res.getString(5));
            }
            ResultSet res2 = conn.ambilData("select *"+"from "+"tbl_kriteria ");
            tabelModelNormalisasi();
            
            while (res2.next()){
                tabelNormalisasi.addRow(new Object[]{res2.getString(1),
                    res2.getString(2),
                    (res2.getFloat(4)*Float.valueOf(max.get(0).toString())),
                    (res2.getFloat(5)*Float.valueOf(max.get(1).toString())),
                    (res2.getFloat(6)*Float.valueOf(max.get(2).toString())),
                    (res2.getFloat(7)*Float.valueOf(max.get(3).toString())),
                    (res2.getFloat(8)*Float.valueOf(max.get(4).toString())),
                    (Float.valueOf(max.get(3).toString())*res2.getFloat(5))});
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public boolean isCellEditable(int row, int column){
        return false;//This causes all cells to be not editable
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProsesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProsesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProsesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProsesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProsesData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kesimpulan;
    private javax.swing.JButton btn_normalisasi;
    private javax.swing.JButton btn_peringkat;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_datawarga;
    private javax.swing.JTable tbl_normalisasi;
    private javax.swing.JTable tbl_peringkat;
    // End of variables declaration//GEN-END:variables
}
